### ISSUE TITLE
Fix multiline examples

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/Docusaurus.Powershell#14]
PlatyPS is not handling multi-line examples correctly like can be seen on this screenshot taken from https://deploy-preview-1--pester-docs.netlify.com/docs/commands/Add-AssertionOperator

![image](https://user-images.githubusercontent.com/230500/71326698-cb572300-24fe-11ea-873a-a9e3bcab9d2f.png)

## Code

<details>
  <summary>The PlatyPS generated markdown with incorrectly closed code fence block responsible for above image</summary>

```markdown
### EXAMPLE 1
\`\`\`powershell
function BeAwesome($ActualValue, [switch] $Negate) {
\`\`\`

\[bool\] $succeeded = $ActualValue -eq 'Awesome'
	if ($Negate) { $succeeded = -not $succeeded }

	if (-not $succeeded)
	{
		if ($Negate)
		{
			$failureMessage = "{$ActualValue} is Awesome"
		}
		else
		{
			$failureMessage = "{$ActualValue} is not Awesome"
		}
	}

	return New-Object psobject -Property @{
		Succeeded      = $succeeded
		FailureMessage = $failureMessage
	}
}

Add-AssertionOperator -Name  BeAwesome `
					-Test  $function:BeAwesome `
					-Alias 'BA'

PS C:\\\> "bad" | should -BeAwesome

{bad} is not Awesome
```
</details>

<details>
  <summary>How the code fence block should look</summary>

```markdown
### EXAMPLE 1
\`\`\`powershell
function BeAwesome($ActualValue, [switch] $Negate) {

\[bool\] $succeeded = $ActualValue -eq 'Awesome'
	if ($Negate) { $succeeded = -not $succeeded }

	if (-not $succeeded)
	{
		if ($Negate)
		{
			$failureMessage = "{$ActualValue} is Awesome"
		}
		else
		{
			$failureMessage = "{$ActualValue} is not Awesome"
		}
	}

	return New-Object psobject -Property @{
		Succeeded      = $succeeded
		FailureMessage = $failureMessage
	}
}

Add-AssertionOperator -Name  BeAwesome `
					-Test  $function:BeAwesome `
					-Alias 'BA'

PS C:\\\> "bad" | should -BeAwesome

{bad} is not Awesome
\`\`\`
```
</details>

## Possible solution

Docusaurus.Powershell already used the [UpdateMarkdownCodeBlock](https://github.com/alt3/Docusaurus.Powershell/blob/master/Source/Private/UpdateMarkdownCodeBlocks.ps1) function function for adding the `powershell` moniker to code fences. 

Perhaps something similar/smart can be done for the multi-line examples.

## Additional Information (and possible solution)
More information on this PlatyPS issue here https://github.com/PowerShell/platyPS/issues/180.

**Comment by vexx32** [comment]
Yeah, the main issue here is that PS comment-help examples expect usage samples, which it expects are a) one line of code, or b) all prefixed with a prompt token (which it recognises as being any line where you have a `>` within the first handful of characters iirc, would have to check that PR, but it was also changed a bit for PS 6.x I think, or definitely for 7.0+).

I don't think there's much PlatyPS can do itself, but for this project's purposes we might want to consider adding a specific token to delimit code blocks / actually using Markdown code block syntax in the comment-help. I don't think the impact to Get-Help's result would be particularly significant, but I could be wrong...

**Comment by bravo-kernel** [comment]
@vexx32 thank you for taking the time to think about this issue, I could do with some help on it so ❤️.

As far as the solution goes, ideally it would not need touching the Get-Help and we would simply transform/fix it in the markdown that is generated by PlatyPs. However, I can also imagine going for a custom tag in the Get-Help. 

Simply put... I welcome all proposals.

**Comment by vexx32** [comment]
Depending on how much whitespace is truncated from what Get-Help can pull, we might experiment with applying extra indentation to code blocks specifically? 🤔

There are a lot of maybes, but I haven't got a lot of time to test it out this week. If we're still stuck on this after the new year I may be able to get a more fully-formed solution put together 🙂

**Comment by bravo-kernel** [comment]
Thanks and no rush, this one needs to solved rock-solid as I would like to prevent various cases failing/displaying wrong. In the most ideal case this would be solved in PlatyPS but perhaps that's a bit too much to ask for.

Anyway, always the new year, happy holidays, I will invest some time in this issues myself as well 🎄

**Comment by bravo-kernel** [comment]
Working on this and it might be possible.

This regex gives me all EXAMPLE nodes: https://regex101.com/r/Nex3Pl/1. 

Then, for each EXAMPLE node:

1. remove the existing closing code-fence
2. insert a new closing code-fence in the correct position

**Comment by bravo-kernel** [comment]
Looks like [the implemented Powershell 7 fix](https://github.com/PowerShell/PowerShell/pull/10776) will only solve this partially. The test files used for the fix [can be download here](https://github.com/PowerShell/PowerShell/files/3744946/test-examples-generation.zip).

Summarized this will only work when multi-line code lines are adjacent like shown below:

```powershell
.EXAMPLE
    PS> Line 1
        Line 2
            Line 3
        Line 4
    Line 5

    Everything after the first empty line (and thus this text) will be treated as the description.

    Which is good for explaining in paragraphs.

   The bad news is that this fix will NOT work for (complex) code examples that themselves contain multiple paragraphs
```

Probably best to keep improving the current guessing mechanism and come to some sort of standard. Pester Mock functions seem to render fine atm (using above regexes)

**Comment by bravo-kernel** [comment]
@vexx32 after testing all possible scenarios, your suggestion of using markdown code fencing turned out to be the best ❤️ . See `Final Solution` above and [this readme](https://github.com/alt3/Docusaurus.Powershell/blob/d5bd980d269ff64b271f2f3b3ba365f17190e114/docusaurus/docs/faq/multi-line-examples.md).  

Would you please let me know if it makes sense/if you would agree.

**Comment by vexx32** [comment]
@bravo-kernel looks pretty good! Nice and thorough 🙂 

I think you should also recognise `` ```ps`` as a code-fence opener, though, as there are a handful of markdown parsers that recognise that as PowerShell as well (e.g., Discord)

Other than that... looks like a pretty solid solution, nice work! 💖

**Comment by bravo-kernel** [comment]
- implemented in [this PR](https://github.com/alt3/Docusaurus.Powershell/pull/17)
- released as [Alt3.Docusaurus.Powershell 1.0.9](https://github.com/alt3/Docusaurus.Powershell/releases/tag/1.0.9)
- end-user [usage instructions](https://docusaurus-powershell.netlify.com/docs/faq/multi-line-examples)
- [detailed step-by-step technical description] above (https://github.com/alt3/Docusaurus.Powershell/issues/14#issuecomment-568552556)

@vexx32 thanks for your input, much appreciated 👍
