### ISSUE TITLE
Module not found by name on unix

### ISSUE THREAD

**Issue by fflaten** [alt3/Docusaurus.Powershell#140]
```powershell
PS /workspaces/docs> Import-Module Alt3.Docusaurus.PowerShell                                                                                  
Import-Module: The specified module 'Alt3.Docusaurus.PowerShell' was not loaded because no valid module file was found in any module directory.
```

Works fine by using `.psd1` path.

**Root cause**:
The module folder still use `Powershell` while the manifest use `PowerShell`. Renaming the folder solves it. I assume that's because the PSGallery registration is using `Powershell`. Possible to rename package on PSGallery?

**Comment by bravo-kernel** [comment]
Omg, another casing surprise 🤦 

Unfortunately, the gallery does not seem to offer a UI option to rename the package so suggestions more than welcome. Would reverting the casing in the manifest be a viable alternative?

![image](https://user-images.githubusercontent.com/230500/198829618-9238a803-e898-445b-ad7b-e2475b337741.png)

**Comment by bravo-kernel** [comment]
Thinking about it could try to `Publish-Module` a new version and passing `-Name`.

Currently [done here without the parameter](https://github.com/alt3/Docusaurus.PowerShell/blob/main/.github/actions/psgallery-publisher/action.ps1#L27).

**Comment by fflaten** [comment]
> Thinking about it, I could try to `Publish-Module` a new version and passing `-Name`.

Different parameter-sets. `-Name` + `-RequiredVersion` is used to select from installed modules instead of specifying by path.

I tried to republish it using `-Path` to a new repo and it gets the expected name.
```
PS /workspaces/docs> Install-Module 'Alt3.Docusaurus.PowerShell'                                
WARNING: 'Alt3.Docusaurus.Powershell' matched module 'Alt3.Docusaurus.Powershell/1.0.30' from provider: 'PowerShellGet', repository 'PSGallery'.
WARNING: 'Alt3.Docusaurus.PowerShell' matched module 'Alt3.Docusaurus.PowerShell/1.0.30' from provider: 'PowerShellGet', repository 'Demo'
```

Per https://developercommunity.visualstudio.com/t/case-change-for-project-name-does-not-change-alrea/1613345 it's by design for nuget feeds. Nuget is not case sensitive, so casing is locked.

> Would reverting the casing in the manifest be a viable alternative?

The `.psd1` has to be perfect match with folder name, so if you can't control the folder (controlled by nuget feed) then it's probably best to revert the casing on filenames. I'd personally change both `psd1` and `psm1` to be consistent and keep it simple. 🙂

**Comment by bravo-kernel** [comment]
Reverted casing for both the module and the Github repo.

New module published as https://github.com/alt3/Docusaurus.Powershell/releases/tag/1.0.31. 

Hope this solves the issue.

**Comment by fflaten** [comment]
Tested ok in pester/docs devcontainer. All good 🙂

**Comment by bravo-kernel** [comment]
Awesome 💃
