### ISSUE TITLE
Period followed by space causes line break in generated comment based help

### ISSUE THREAD

**Issue by beau-witter** [alt3/Docusaurus.Powershell#151]
Following the discussion on [this pr](https://github.com/pester/docs/pull/212#discussion_r906861973) and noticing that this is still persisting https://pester.dev/docs/commands/New-PesterConfiguration#description it seems like there is still a regex that is a little too eager to help.

Unless the Pester 5.4.0 docs are not using the latest Alt3.Docusaurus.Powershell (which I cannot seem to tell what version it is using) then there may still be something amiss with that part of the generation.

**Comment by bravo-kernel** [comment]
The Pester 5.4.0 docs were generated using the latest Alt3-module.

I do not get what issue you are seeing here to be honest. Could provide an example or extend the test case at https://github.com/alt3/Docusaurus.Powershell/tree/main/Tests/Integration/CrossVersionCodeExamples?

**Comment by beau-witter** [comment]
Here is the example that I was referencing:
Generated: 
![image](https://user-images.githubusercontent.com/26094186/220275443-805c3708-cbaf-4ab9-8941-afd7786cc48f.png)
Source:
![image](https://user-images.githubusercontent.com/26094186/220275655-9c2ff2e5-44c7-4a31-a93a-42fd4c1299f7.png)

From the looks of it, this was identified in the PR I linked, but it seems that there has not been a fix for it yet. Like I noted in the title, it appears to happen whenever the text inside the description contains multiple sentences inside the triple-backtick code block.

I will also look into extending the test case at that link.

**Comment by bravo-kernel** [comment]
Thanks, I see now and totally missed that. Much appreciated 👍

**Comment by bravo-kernel** [comment]
Below image shows the raw output as produced by PlatyPs.

As you can see the linebreaks are already inserted before the Alt3 (post-processor) module ever touches it.

![image](https://user-images.githubusercontent.com/230500/226109871-96ef8122-f34a-4d85-9c03-4ba9954dbd99.png)

I think this should be solved in PlatyPS because there is no way we can "guess" whether the line breaks in the generated PlatyPS file are intentional or an error. 

@fflaten

**Comment by fflaten** [comment]
> I think this should be solved in PlatyPS because there is no way we can "guess" whether the line breaks in the generated PlatyPS file are intentional or an error.

+1 👍 Tested with platyPS 2.0-preview? If it's the same, will either of you report in their [repo](https://github.com/PowerShell/platyPS)?

**Comment by bravo-kernel** [comment]
I have tried to test with platy 2 some time ago but failed. The Alt3 module no longer runs after using v2. I was hoping to request your help some day, after I have cleaned up the current version.

**Comment by bravo-kernel** [comment]
I totally forgot but `New-DocusaurusHelp` outputs a `Get-Item` list of created files. The idea back then was that one could create custom post-processing to apply any site-specific fixes.

In this case, Pester docs [generate-command-reference.ps1](https://github.com/pester/docs/blob/master/generate-command-reference.ps1) could be extended to fix the options in `New-PesterConfiguration.mdx`. That way, the fix will stick forever.

![image](https://user-images.githubusercontent.com/230500/226178952-6e8a7444-06f7-4b71-96c1-794dcbdc1c3a.png)

**Comment by bravo-kernel** [comment]
Closing as this cannot be solved by the Alt3 module and solution is provided above.
