### ISSUE TITLE
Exception when Append/PrependMarkdown includes certain wildcard characters

### ISSUE THREAD

**Issue by fflaten** [alt3/Docusaurus.Powershell#160]
![image](https://user-images.githubusercontent.com/3436158/227792751-39e52768-d142-4e19-a1b9-a97da7cd8dd5.png)

Exception is thrown by `Test-Path` [here](https://github.com/alt3/Docusaurus.Powershell/blob/0cefb982df2124caac63b098023acd975ae956a1/Source/Private/InsertUserMarkdown.ps1#LL20C14-L20C14)
Can repro with same string using `Test-Path` in unix only (pester/docs devcontainer).

```ps1
$t = @"
:::note This page was generated using the comment based help in Pester $($ModuleList.Pester).
To edit the content of this page, change the corresponding help in the [pester/pester](https://github.com/pester/pester)-repository.
:::
"@

Test-Path $t
```

Using `Test-Path -LiteralPath $t` doesn't throw, but maybe better to check if string is a path first?
Haven't really identified the issue as you can solve it by any of these ways:
- Remove `:::` prefix
- Remove `/` in the link name
- Remove square brackets in link (which are wildcard chars, so that makes sense)

**Comment by bravo-kernel** [comment]
Would you mind just adding any of the solutions as you see fit?

Sent from my Mobile Device

**Comment by bravo-kernel** [comment]
If you have an example of how to check if string is really a path, let me know and I will make a new version.

**Comment by fflaten** [comment]
Was about to suggest `Test-Path $t -IsValid`, but it's actually true with `:::` prefix which is probably why some provider-code with wildcard-support is executed.

You could maybe just catch the exception like suggested here: https://ss64.com/ps/test-path.html

**Comment by bravo-kernel** [comment]
Awesome, will add that when I find the time 👍 because while we are doing all this, I am also being flooded with this https://github.com/alt3/rank-my-wallet/blob/main/contributing.md#translations

**Comment by bravo-kernel** [comment]
Fix released with https://github.com/alt3/Docusaurus.Powershell/releases/tag/1.0.34. Thanks for the pointer 👍
